export const defaultQuestions = [
  {
    id: 'q-1',
    image_url: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80',
    aircraft_type: 'Airbus A320-200',
    airline: 'Korean Air',
    registration: 'HL8253',
    difficulty: 'easy',
    option_a: 'Airbus A320-200',
    option_b: 'Airbus A321-200',
    option_c: 'Boeing 737-800',
    option_d: 'Boeing 777-300ER',
    correct_answer: 'Airbus A320-200',
    hint: 'Short-to-medium haul narrow-body twinjet.',
    explanation: 'The aircraft has a narrow-body fuselage and a typical Airbus A320 family look with two engines mounted under the wings.',
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'q-2',
    image_url: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80',
    aircraft_type: 'Boeing 737-800',
    airline: 'Asiana Airlines',
    registration: 'HL8315',
    difficulty: 'easy',
    option_a: 'Boeing 737-800',
    option_b: 'Airbus A330-300',
    option_c: 'Airbus A321-200',
    option_d: 'Boeing 787-9',
    correct_answer: 'Boeing 737-800',
    hint: 'The classic narrow-body with a more rounded nose profile and a 737 family wing design.',
    explanation: 'The 737-800 is a narrow-body workhorse with a distinct fuselage and engine placement that matches the aircraft in the image.',
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'q-3',
    image_url: 'https://images.unsplash.com/photo-1556388158-d0d5d8f9f85d?auto=format&fit=crop&w=1200&q=80',
    aircraft_type: 'Airbus A330-300',
    airline: 'Cathay Pacific',
    registration: 'B-HLL',
    difficulty: 'medium',
    option_a: 'Airbus A330-300',
    option_b: 'Boeing 787-9',
    option_c: 'Boeing 777-200ER',
    option_d: 'Airbus A350-900',
    correct_answer: 'Airbus A330-300',
    hint: 'A wide-body twin-engine aircraft often used for long-haul flights.',
    explanation: 'The A330-300 has a wide-body fuselage and a distinctive air intake arrangement and wing sweep associated with Airbus wide-bodies.',
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'q-4',
    image_url: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80',
    aircraft_type: 'Boeing 777-300ER',
    airline: 'Emirates',
    registration: 'A6-EQV',
    difficulty: 'hard',
    option_a: 'Boeing 777-300ER',
    option_b: 'Airbus A350-900',
    option_c: 'Boeing 787-8',
    option_d: 'Airbus A340-300',
    correct_answer: 'Boeing 777-300ER',
    hint: 'This ultra-long-range twinjet has a very wide body and large engines.',
    explanation: 'The 777-300ER is one of the most recognizable wide-body aircraft, with its distinctive long upper deck and large high-bypass engines.',
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'q-5',
    image_url: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80',
    aircraft_type: 'Airbus A321-200',
    airline: 'JetBlue',
    registration: 'N968JT',
    difficulty: 'medium',
    option_a: 'Airbus A321-200',
    option_b: 'Airbus A320-200',
    option_c: 'Boeing 737 MAX 8',
    option_d: 'Airbus A319-100',
    correct_answer: 'Airbus A321-200',
    hint: 'A longer narrow-body variant than the A320 with a stretched fuselage.',
    explanation: 'The Airbus A321-200 is identified by its notably longer body compared to an A320 and its characteristic Airbus family styling.',
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'q-6',
    image_url: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80',
    aircraft_type: 'Boeing 737 MAX 8',
    airline: 'Southwest Airlines',
    registration: 'N8951Q',
    difficulty: 'hard',
    option_a: 'Boeing 737 MAX 8',
    option_b: 'Boeing 737-800',
    option_c: 'Airbus A320neo',
    option_d: 'Airbus A321neo',
    correct_answer: 'Boeing 737 MAX 8',
    hint: 'The MAX family retains the same general shape but has distinctive curved winglets and updated engines.',
    explanation: 'The MAX 8 features the latest generation 737 fuselage and wing design, making it a common variant used by low-cost carriers.',
    published: true,
    created_at: new Date().toISOString()
  }
];

export const defaultAircraftEntries = [
  {
    id: 'entry-airbus-a320',
    category: 'Airbus',
    name: 'Airbus A320',
    manufacturer: 'Airbus',
    first_flight: '1987',
    typical_capacity: '150-180 passengers',
    range: '3,300-6,100 km',
    facts: ['Best-selling single-aisle aircraft family', 'Popular on short and medium-haul routes', 'Known for efficient fuel use and wide cabin'],
    image_url: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'entry-boeing-737',
    category: 'Boeing',
    name: 'Boeing 737-800',
    manufacturer: 'Boeing',
    first_flight: '1997',
    typical_capacity: '162-189 passengers',
    range: '5,000-5,600 km',
    facts: ['Widely used on domestic and regional operations', 'Classic 737 family design', 'Common among low-cost and flag carriers'],
    image_url: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'entry-embraer-190',
    category: 'Embraer',
    name: 'Embraer E190',
    manufacturer: 'Embraer',
    first_flight: '2004',
    typical_capacity: '96-114 passengers',
    range: '3,500-4,500 km',
    facts: ['Efficient regional jet with strong fuel economy', 'Common on short to medium-haul routes', 'High reliability in regional operations'],
    image_url: 'https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'entry-atr-72',
    category: 'ATR',
    name: 'ATR 72',
    manufacturer: 'ATR',
    first_flight: '1988',
    typical_capacity: '64-78 passengers',
    range: '1,000-1,600 km',
    facts: ['Twin-turboprop regional airliner', 'Excellent short-runway performance', 'Common on island and regional services'],
    image_url: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'entry-bombardier-cs300',
    category: 'Bombardier',
    name: 'A220-300',
    manufacturer: 'Airbus',
    first_flight: '2016',
    typical_capacity: '130-160 passengers',
    range: '5,500-6,300 km',
    facts: ['Modern single-aisle airliner with efficient aerodynamics', 'Designed for regional and transcontinental routes', 'Interior provides excellent cabin comfort'],
    image_url: 'https://images.unsplash.com/photo-1556388158-d0d5d8f9f85d?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'entry-other',
    category: 'Other',
    name: 'De Havilland Dash 8',
    manufacturer: 'De Havilland Canada',
    first_flight: '1983',
    typical_capacity: '36-78 passengers',
    range: '1,500-3,800 km',
    facts: ['Highly versatile turboprop airliner', 'Used for regional service and cargo missions', 'Known for rugged operations and versatility'],
    image_url: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80'
  }
];
